/**
 * Scenario presets and city baseline data
 *
 * All baseline values are illustrative proxies for 2024.
 * Wage data based on ABS Average Weekly Earnings & regional variations.
 * Replace with official ABS / RBA / CoreLogic data for production.
 */

import type { CityBaseState, PolicyLeversV2, ScenarioParams } from "./methodology";
import type { CityId, StateId } from "./regions";
import { CITIES, cityMeta, getCitiesByState } from "./regions";
import { DEFAULT_POLICY_LEVERS_V2 } from "./policyRegistry";

/**
 * City baseline states for all major Australian cities.
 * Wage figures are median full-time annual wages (2024 estimates).
 * Values are illustrative proxies — replace with official data.
 */
export const CITY_BASELINES: Record<CityId, CityBaseState> = {
  // ============ CAPITALS ============
  SYD: {
    cityId: "SYD",
    cityName: "Sydney",
    year0: 2024,
    population: 5_450_000,
    netMigrationPerYear: 85_000,
    naturalPopGrowthRate: 0.006,
    dwellingStock: 2_050_000,
    annualCompletions: 38_000,
    demolitionRate: 0.002,
    medianPrice: 1_150_000,
    medianAnnualRent: 32_500,
    medianAnnualWage: 95_000,  // High due to finance/tech concentration
    wageGrowthRate: 0.032,     // 3.2% annual growth
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.32,
  },
  MEL: {
    cityId: "MEL",
    cityName: "Melbourne",
    year0: 2024,
    population: 5_200_000,
    netMigrationPerYear: 95_000,
    naturalPopGrowthRate: 0.006,
    dwellingStock: 1_950_000,
    annualCompletions: 42_000,
    demolitionRate: 0.002,
    medianPrice: 920_000,
    medianAnnualRent: 26_000,
    medianAnnualWage: 89_000,
    wageGrowthRate: 0.030,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.30,
  },
  BNE: {
    cityId: "BNE",
    cityName: "Brisbane",
    year0: 2024,
    population: 2_600_000,
    netMigrationPerYear: 55_000,
    naturalPopGrowthRate: 0.006,
    dwellingStock: 980_000,
    annualCompletions: 24_000,
    demolitionRate: 0.002,
    medianPrice: 850_000,
    medianAnnualRent: 28_600,
    medianAnnualWage: 85_000,
    wageGrowthRate: 0.033,     // Strong growth, Olympics effect
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.28,
  },
  PER: {
    cityId: "PER",
    cityName: "Perth",
    year0: 2024,
    population: 2_200_000,
    netMigrationPerYear: 35_000,
    naturalPopGrowthRate: 0.007,
    dwellingStock: 850_000,
    annualCompletions: 18_000,
    demolitionRate: 0.002,
    medianPrice: 720_000,
    medianAnnualRent: 28_600,
    medianAnnualWage: 98_000,  // High due to mining industry
    wageGrowthRate: 0.035,     // Mining boom influence
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.26,
  },
  ADL: {
    cityId: "ADL",
    cityName: "Adelaide",
    year0: 2024,
    population: 1_420_000,
    netMigrationPerYear: 18_000,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 580_000,
    annualCompletions: 11_000,
    demolitionRate: 0.002,
    medianPrice: 750_000,
    medianAnnualRent: 26_000,
    medianAnnualWage: 80_000,
    wageGrowthRate: 0.028,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.27,
  },
  HBA: {
    cityId: "HBA",
    cityName: "Hobart",
    year0: 2024,
    population: 250_000,
    netMigrationPerYear: 3_500,
    naturalPopGrowthRate: 0.004,
    dwellingStock: 105_000,
    annualCompletions: 2_200,
    demolitionRate: 0.002,
    medianPrice: 680_000,
    medianAnnualRent: 26_000,
    medianAnnualWage: 76_000,
    wageGrowthRate: 0.026,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.24,
  },
  DRW: {
    cityId: "DRW",
    cityName: "Darwin",
    year0: 2024,
    population: 145_000,
    netMigrationPerYear: 1_500,
    naturalPopGrowthRate: 0.008,
    dwellingStock: 58_000,
    annualCompletions: 1_200,
    demolitionRate: 0.003,
    medianPrice: 520_000,
    medianAnnualRent: 28_600,
    medianAnnualWage: 92_000,  // High due to resources/government
    wageGrowthRate: 0.030,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.30,
  },
  CBR: {
    cityId: "CBR",
    cityName: "Canberra",
    year0: 2024,
    population: 470_000,
    netMigrationPerYear: 8_000,
    naturalPopGrowthRate: 0.006,
    dwellingStock: 185_000,
    annualCompletions: 4_500,
    demolitionRate: 0.002,
    medianPrice: 880_000,
    medianAnnualRent: 31_200,
    medianAnnualWage: 102_000, // Highest - public service concentration
    wageGrowthRate: 0.028,     // Stable public sector growth
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.25,
  },

  // ============ NSW MAJOR CITIES ============
  NCL: {
    cityId: "NCL",
    cityName: "Newcastle",
    year0: 2024,
    population: 340_000,
    netMigrationPerYear: 5_000,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 145_000,
    annualCompletions: 2_800,
    demolitionRate: 0.002,
    medianPrice: 780_000,
    medianAnnualRent: 26_000,
    medianAnnualWage: 82_000,
    wageGrowthRate: 0.029,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.28,
  },
  WOL: {
    cityId: "WOL",
    cityName: "Wollongong",
    year0: 2024,
    population: 320_000,
    netMigrationPerYear: 4_000,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 135_000,
    annualCompletions: 2_400,
    demolitionRate: 0.002,
    medianPrice: 920_000,
    medianAnnualRent: 27_300,
    medianAnnualWage: 81_000,
    wageGrowthRate: 0.028,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.27,
  },
  ALW: {
    cityId: "ALW",
    cityName: "Albury–Wodonga",
    year0: 2024,
    population: 95_000,
    netMigrationPerYear: 1_500,
    naturalPopGrowthRate: 0.004,
    dwellingStock: 42_000,
    annualCompletions: 800,
    demolitionRate: 0.002,
    medianPrice: 550_000,
    medianAnnualRent: 22_100,
    medianAnnualWage: 72_000,
    wageGrowthRate: 0.026,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.24,
  },

  // ============ VIC MAJOR CITIES ============
  GEL: {
    cityId: "GEL",
    cityName: "Geelong",
    year0: 2024,
    population: 290_000,
    netMigrationPerYear: 6_000,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 125_000,
    annualCompletions: 3_000,
    demolitionRate: 0.002,
    medianPrice: 720_000,
    medianAnnualRent: 24_700,
    medianAnnualWage: 78_000,
    wageGrowthRate: 0.029,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.26,
  },
  BAL: {
    cityId: "BAL",
    cityName: "Ballarat",
    year0: 2024,
    population: 120_000,
    netMigrationPerYear: 2_500,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 52_000,
    annualCompletions: 1_200,
    demolitionRate: 0.002,
    medianPrice: 550_000,
    medianAnnualRent: 22_100,
    medianAnnualWage: 72_000,
    wageGrowthRate: 0.027,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.24,
  },
  BEN: {
    cityId: "BEN",
    cityName: "Bendigo",
    year0: 2024,
    population: 115_000,
    netMigrationPerYear: 2_200,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 50_000,
    annualCompletions: 1_100,
    demolitionRate: 0.002,
    medianPrice: 520_000,
    medianAnnualRent: 21_600,
    medianAnnualWage: 71_000,
    wageGrowthRate: 0.026,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.23,
  },

  // ============ QLD MAJOR CITIES ============
  GC: {
    cityId: "GC",
    cityName: "Gold Coast",
    year0: 2024,
    population: 720_000,
    netMigrationPerYear: 18_000,
    naturalPopGrowthRate: 0.006,
    dwellingStock: 310_000,
    annualCompletions: 8_500,
    demolitionRate: 0.002,
    medianPrice: 950_000,
    medianAnnualRent: 31_200,
    medianAnnualWage: 78_000,  // Tourism/hospitality mix
    wageGrowthRate: 0.030,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.35,
  },
  SC: {
    cityId: "SC",
    cityName: "Sunshine Coast",
    year0: 2024,
    population: 380_000,
    netMigrationPerYear: 10_000,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 165_000,
    annualCompletions: 4_500,
    demolitionRate: 0.002,
    medianPrice: 920_000,
    medianAnnualRent: 29_900,
    medianAnnualWage: 75_000,
    wageGrowthRate: 0.029,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.32,
  },
  TSV: {
    cityId: "TSV",
    cityName: "Townsville",
    year0: 2024,
    population: 195_000,
    netMigrationPerYear: 2_500,
    naturalPopGrowthRate: 0.006,
    dwellingStock: 82_000,
    annualCompletions: 1_800,
    demolitionRate: 0.002,
    medianPrice: 420_000,
    medianAnnualRent: 22_100,
    medianAnnualWage: 78_000,  // Defence/resources
    wageGrowthRate: 0.028,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.26,
  },
  CNS: {
    cityId: "CNS",
    cityName: "Cairns",
    year0: 2024,
    population: 165_000,
    netMigrationPerYear: 2_800,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 72_000,
    annualCompletions: 1_600,
    demolitionRate: 0.002,
    medianPrice: 520_000,
    medianAnnualRent: 24_700,
    medianAnnualWage: 72_000,  // Tourism-heavy
    wageGrowthRate: 0.027,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.30,
  },
  TWB: {
    cityId: "TWB",
    cityName: "Toowoomba",
    year0: 2024,
    population: 145_000,
    netMigrationPerYear: 2_000,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 62_000,
    annualCompletions: 1_400,
    demolitionRate: 0.002,
    medianPrice: 550_000,
    medianAnnualRent: 23_400,
    medianAnnualWage: 74_000,
    wageGrowthRate: 0.028,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.25,
  },
  MKY: {
    cityId: "MKY",
    cityName: "Mackay",
    year0: 2024,
    population: 82_000,
    netMigrationPerYear: 800,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 36_000,
    annualCompletions: 700,
    demolitionRate: 0.002,
    medianPrice: 450_000,
    medianAnnualRent: 23_400,
    medianAnnualWage: 88_000,  // Mining town premium
    wageGrowthRate: 0.032,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.24,
  },
  ROP: {
    cityId: "ROP",
    cityName: "Rockhampton",
    year0: 2024,
    population: 85_000,
    netMigrationPerYear: 600,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 38_000,
    annualCompletions: 750,
    demolitionRate: 0.002,
    medianPrice: 400_000,
    medianAnnualRent: 21_600,
    medianAnnualWage: 76_000,
    wageGrowthRate: 0.027,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.23,
  },

  // ============ TAS MAJOR CITIES ============
  LST: {
    cityId: "LST",
    cityName: "Launceston",
    year0: 2024,
    population: 90_000,
    netMigrationPerYear: 1_200,
    naturalPopGrowthRate: 0.003,
    dwellingStock: 42_000,
    annualCompletions: 900,
    demolitionRate: 0.002,
    medianPrice: 520_000,
    medianAnnualRent: 22_100,
    medianAnnualWage: 70_000,
    wageGrowthRate: 0.025,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.22,
  },

  // ============ WA MAJOR CITIES ============
  BUN: {
    cityId: "BUN",
    cityName: "Bunbury",
    year0: 2024,
    population: 78_000,
    netMigrationPerYear: 1_000,
    naturalPopGrowthRate: 0.005,
    dwellingStock: 35_000,
    annualCompletions: 800,
    demolitionRate: 0.002,
    medianPrice: 520_000,
    medianAnnualRent: 24_700,
    medianAnnualWage: 82_000,  // Mining/resources influence
    wageGrowthRate: 0.030,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.24,
  },

  // ============ EXPANDED REGIONAL CENTRES ============
  // NSW
  CCS: {
    cityId: "CCS",
    cityName: "Central Coast",
    year0: 2024,
    population: 350_000,
    netMigrationPerYear: 4_500,
    naturalPopGrowthRate: 0.004,
    dwellingStock: 155_000,
    annualCompletions: 2_700,
    demolitionRate: 0.002,
    medianPrice: 820_000,
    medianAnnualRent: 25_000,
    medianAnnualWage: 80_000,
    wageGrowthRate: 0.028,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.28,
  },
  WGA: {
    cityId: "WGA",
    cityName: "Wagga Wagga",
    year0: 2024,
    population: 75_000,
    netMigrationPerYear: 1_200,
    naturalPopGrowthRate: 0.004,
    dwellingStock: 34_000,
    annualCompletions: 650,
    demolitionRate: 0.002,
    medianPrice: 520_000,
    medianAnnualRent: 22_500,
    medianAnnualWage: 74_000,
    wageGrowthRate: 0.026,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.24,
  },
  // VIC
  SHP: {
    cityId: "SHP",
    cityName: "Shepparton",
    year0: 2024,
    population: 70_000,
    netMigrationPerYear: 900,
    naturalPopGrowthRate: 0.004,
    dwellingStock: 30_000,
    annualCompletions: 600,
    demolitionRate: 0.002,
    medianPrice: 480_000,
    medianAnnualRent: 21_800,
    medianAnnualWage: 73_000,
    wageGrowthRate: 0.026,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.23,
  },
  // QLD
  BDG: {
    cityId: "BDG",
    cityName: "Bundaberg",
    year0: 2024,
    population: 105_000,
    netMigrationPerYear: 1_400,
    naturalPopGrowthRate: 0.004,
    dwellingStock: 50_000,
    annualCompletions: 850,
    demolitionRate: 0.002,
    medianPrice: 520_000,
    medianAnnualRent: 24_000,
    medianAnnualWage: 72_000,
    wageGrowthRate: 0.027,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.26,
  },
  HVB: {
    cityId: "HVB",
    cityName: "Hervey Bay",
    year0: 2024,
    population: 60_000,
    netMigrationPerYear: 1_000,
    naturalPopGrowthRate: 0.004,
    dwellingStock: 28_000,
    annualCompletions: 520,
    demolitionRate: 0.002,
    medianPrice: 560_000,
    medianAnnualRent: 24_700,
    medianAnnualWage: 70_000,
    wageGrowthRate: 0.027,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.27,
  },
  GLA: {
    cityId: "GLA",
    cityName: "Gladstone",
    year0: 2024,
    population: 65_000,
    netMigrationPerYear: 900,
    naturalPopGrowthRate: 0.004,
    dwellingStock: 30_000,
    annualCompletions: 540,
    demolitionRate: 0.002,
    medianPrice: 520_000,
    medianAnnualRent: 24_700,
    medianAnnualWage: 78_000,
    wageGrowthRate: 0.028,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.25,
  },
  // WA
  KAL: {
    cityId: "KAL",
    cityName: "Kalgoorlie–Boulder",
    year0: 2024,
    population: 30_000,
    netMigrationPerYear: 400,
    naturalPopGrowthRate: 0.004,
    dwellingStock: 14_000,
    annualCompletions: 220,
    demolitionRate: 0.002,
    medianPrice: 380_000,
    medianAnnualRent: 21_500,
    medianAnnualWage: 85_000,
    wageGrowthRate: 0.030,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.26,
  },
  // SA
  MTG: {
    cityId: "MTG",
    cityName: "Mount Gambier",
    year0: 2024,
    population: 30_000,
    netMigrationPerYear: 350,
    naturalPopGrowthRate: 0.003,
    dwellingStock: 14_000,
    annualCompletions: 220,
    demolitionRate: 0.002,
    medianPrice: 420_000,
    medianAnnualRent: 20_800,
    medianAnnualWage: 70_000,
    wageGrowthRate: 0.024,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.22,
  },
  // NT
  ASP: {
    cityId: "ASP",
    cityName: "Alice Springs",
    year0: 2024,
    population: 25_000,
    netMigrationPerYear: 200,
    naturalPopGrowthRate: 0.003,
    dwellingStock: 10_500,
    annualCompletions: 180,
    demolitionRate: 0.003,
    medianPrice: 430_000,
    medianAnnualRent: 24_700,
    medianAnnualWage: 82_000,
    wageGrowthRate: 0.026,
    wageIndex: 100,
    cpiIndex: 100,
    mortgageRate: 0.065,
    mortgageTermYears: 30,
    investorDwellingShare: 0.28,
  },
};

/**
 * Get all city baselines as an array
 */
export function getAllCityBaselines(): CityBaseState[] {
  return Object.values(CITY_BASELINES);
}

/**
 * Get capital city baselines only
 */
export function getCapitalBaselines(): CityBaseState[] {
  return CITIES.filter((c) => c.isCapital).map((c) => CITY_BASELINES[c.id]);
}

/**
 * Get baselines for cities in a specific state
 */
export function getStateBaselines(state: StateId): CityBaseState[] {
  return getCitiesByState(state).map((c) => CITY_BASELINES[c.id]);
}

/**
 * Default (no-change) policy levers
 */
export const DEFAULT_POLICY_LEVERS: PolicyLeversV2 = { ...DEFAULT_POLICY_LEVERS_V2 };

/**
 * Named scenario presets
 */
export interface ScenarioPreset {
  id: string;
  name: string;
  description: string;
  policy: PolicyLeversV2;
  years?: number;
}

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: "baseline",
    name: "Baseline (No Change)",
    description: "Business as usual — no policy changes. Shows how current trends compound.",
    policy: { ...DEFAULT_POLICY_LEVERS },
    years: 20,
  },
  {
    id: "ng-remove",
    name: "Remove Negative Gearing",
    description:
      "Phase out negative gearing for new purchases over 5 years. Existing arrangements grandfathered.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      negativeGearingMode: "remove",
      negativeGearingIntensity: 1,
      rampYears: 5,
    },
    years: 15,
  },
  {
    id: "ng-remove-fast",
    name: "Remove Negative Gearing (Immediate)",
    description: "Immediate removal of negative gearing — no phase-in period.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      negativeGearingMode: "remove",
      negativeGearingIntensity: 1,
      rampYears: 0,
    },
    years: 15,
  },
  {
    id: "ng-restore",
    name: "Restore Negative Gearing",
    description:
      "Model the effect of restoring negative gearing if it were previously removed.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      negativeGearingMode: "reverse",
      negativeGearingIntensity: 1,
      rampYears: 3,
    },
    years: 15,
  },
  {
    id: "ownership-cap",
    name: "Ownership Cap (1 PPOR + 1 IP)",
    description:
      "Limit individuals to 1 principal residence + 1 investment property.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      ownershipCapEnabled: true,
      ownershipCapEnforcement: 1,
      excessInvestorStockShare: 0.20,
      divestmentPhased: true,
      rampYears: 5,
    },
    years: 15,
  },
  {
    id: "ownership-cap-aggressive",
    name: "Ownership Cap (Aggressive)",
    description: "Same cap, but faster enforcement and shorter ramp.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      ownershipCapEnabled: true,
      ownershipCapEnforcement: 1,
      excessInvestorStockShare: 0.25,
      divestmentPhased: false,
      rampYears: 2,
    },
    years: 15,
  },
  {
    id: "ng-remove-plus-cap",
    name: "Remove NG + Ownership Cap",
    description:
      "Combined reform: phase out negative gearing AND enforce ownership cap.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      negativeGearingMode: "remove",
      negativeGearingIntensity: 1,
      ownershipCapEnabled: true,
      ownershipCapEnforcement: 1,
      excessInvestorStockShare: 0.20,
      divestmentPhased: true,
      rampYears: 5,
    },
    years: 20,
  },
  {
    id: "supply-boost",
    name: "Supply Boost (+20%)",
    description: "Increase housing completions by 20% through planning reforms.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      supplyBoost: 0.20,
    },
    years: 20,
  },
  {
    id: "supply-boost-plus-ng",
    name: "Supply Boost + Remove NG",
    description: "Combined supply and demand-side reform.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      supplyBoost: 0.15,
      negativeGearingMode: "remove",
      negativeGearingIntensity: 1,
      rampYears: 5,
    },
    years: 20,
  },
  {
    id: "comprehensive",
    name: "Comprehensive Reform",
    description:
      "Full reform: supply boost, negative gearing removal, ownership cap.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      supplyBoost: 0.15,
      negativeGearingMode: "remove",
      negativeGearingIntensity: 1,
      ownershipCapEnabled: true,
      ownershipCapEnforcement: 1,
      excessInvestorStockShare: 0.18,
      divestmentPhased: true,
      stampDutyRateDelta: -0.01,
      rampYears: 5,
    },
    years: 20,
  },
  {
    id: "land-tax-transition",
    name: "Land tax transition (stamp duty → land tax)",
    description: "Reduce transaction frictions by shifting away from stamp duty toward land tax (proxy).",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      taxInvestor: { ...DEFAULT_POLICY_LEVERS.taxInvestor, landTaxShift: 0.8 },
      rampYears: 7,
    },
    years: 25,
  },
  {
    id: "macroprudential-tightening",
    name: "Macroprudential tightening",
    description: "Tighten credit conditions (serviceability buffer + DTI + investor lending limits).",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      credit: {
        ...DEFAULT_POLICY_LEVERS.credit,
        serviceabilityBufferDelta: 0.01,
        dtiCapTightness: 0.6,
        investorLendingLimitTightness: 0.5,
      },
      rampYears: 1,
    },
    years: 15,
  },
  {
    id: "short-stay-clampdown",
    name: "Short-stay clampdown",
    description: "Shift a bounded share of short-stay stock back into long-term rentals (proxy).",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      taxInvestor: {
        ...DEFAULT_POLICY_LEVERS.taxInvestor,
        shortStayRegulationIntensity: 0.8,
        vacancyTaxIntensity: 0.4,
      },
      rampYears: 2,
    },
    years: 12,
  },
  {
    id: "public-housing-build",
    name: "Public housing build program",
    description: "Add public/community housing completions (bounded) to relieve rental pressure (proxy).",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      publicCommunity: { ...DEFAULT_POLICY_LEVERS.publicCommunity, publicHousingBuildBoost: 0.10 },
      rampYears: 3,
    },
    years: 20,
  },
  {
    id: "migration-shock-down",
    name: "Migration shock (lower)",
    description: "Reduce net overseas migration levels (proxy shock) to reduce demand pressure.",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      migration: { ...DEFAULT_POLICY_LEVERS.migration, netOverseasMigrationShock: -0.15 },
      rampYears: 0,
    },
    years: 12,
  },
  {
    id: "all-levers",
    name: "All levers (comprehensive + expert)",
    description:
      "Stress test: activates multiple calibration-first levers alongside core reforms (bounded, shape-first).",
    policy: {
      ...DEFAULT_POLICY_LEVERS,
      supplyBoost: 0.12,
      negativeGearingMode: "remove",
      negativeGearingIntensity: 1,
      ownershipCapEnabled: true,
      ownershipCapEnforcement: 1,
      excessInvestorStockShare: 0.18,
      divestmentPhased: true,
      taxInvestor: {
        ...DEFAULT_POLICY_LEVERS.taxInvestor,
        cgtDiscountDelta: -0.10,
        landTaxShift: 0.6,
        vacancyTaxIntensity: 0.5,
        shortStayRegulationIntensity: 0.6,
        foreignBuyerRestrictionIntensity: 0.5,
      },
      credit: {
        ...DEFAULT_POLICY_LEVERS.credit,
        serviceabilityBufferDelta: 0.01,
        dtiCapTightness: 0.5,
        investorLendingLimitTightness: 0.4,
      },
      rental: {
        ...DEFAULT_POLICY_LEVERS.rental,
        rentAssistanceIntensity: 0.4,
        rentRegulationCap: 0.04,
        rentRegulationCoverage: 0.4,
        vacancyDecontrol: true,
      },
      planning: {
        ...DEFAULT_POLICY_LEVERS.planning,
        upzoningIntensity: 0.6,
        infrastructureEnablement: 0.6,
        infrastructureLagYears: 3,
      },
      publicCommunity: {
        ...DEFAULT_POLICY_LEVERS.publicCommunity,
        publicHousingBuildBoost: 0.08,
      },
      migration: { ...DEFAULT_POLICY_LEVERS.migration, netOverseasMigrationShock: -0.05 },
      rampYears: 5,
    },
    years: 25,
  },
];

export function getPreset(id: string): ScenarioPreset | undefined {
  return SCENARIO_PRESETS.find((p) => p.id === id);
}

export function buildScenarioFromPreset(presetId: string, includeAllCities = true): ScenarioParams {
  const preset = getPreset(presetId);
  if (!preset) {
    throw new Error(`Unknown preset: ${presetId}`);
  }
  return {
    years: preset.years ?? 20,
    cities: includeAllCities ? getAllCityBaselines() : getCapitalBaselines(),
    policy: preset.policy,
  };
}

export function buildDefaultScenario(years: number = 20, includeAllCities = true): ScenarioParams {
  return {
    years,
    cities: includeAllCities ? getAllCityBaselines() : getCapitalBaselines(),
    policy: DEFAULT_POLICY_LEVERS,
  };
}
